kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: cicd # 定义流水线名称
  
steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: package # 流水线名称
    pull: if-not-exists
    image: python:3.10-slim # 定义创建容器的Docker镜像
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: bisheng-cache
        path: /app/build # 将应用打包好的Jar和执行脚本挂载出来
    environment:
      NEXUS_USER:
        from_secret: NEXUS_USER
      NEXUS_PASSWORD:
        from_secret: NEXUS_PASSWORD
      REPO:
        from_secret: PY_NEXUS
    commands: # 定义在Docker容器中执行的shell命令
      - pip install Cython
      - pip install wheel
      - pip install twine
      - cd ./src/bisheng-langchain
      - python setup.py bdist_wheel
      - twine upload --verbose -u $NEXUS_USER  -p $NEXUS_PASSWORD --repository-url $REPO  dist/*.whl
  
  - name: set poetry
    pull: if-not-exists
    image: golang
    environment:
      NEXUS_PUBLIC:
        from_secret: NEXUS_PUBLIC
      NEXUS_PUBLIC_PASSWORD:
        from_secret: NEXUS_PUBLIC_PASSWORD
      REPO:
        from_secret: PY_NEXUS
      PROXY:
        from_secret: APT-GET
    commands:
    - cd ./src/backend/
    - echo $REPO
    - REPO2=$(echo $REPO | sed 's/http:\\/\\///g')
    - sed -i '6i\RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple' Dockerfile
    - sed -i '23i\RUN poetry source add --priority=supplemental foo http://'$NEXUS_PUBLIC':'$NEXUS_PUBLIC_PASSWORD'@'$REPO2'simple' Dockerfile
    - sed -i '23i\RUN poetry source add --priority=primary qh https://pypi.tuna.tsinghua.edu.cn/simple' Dockerfile
    - cat Dockerfile
    
  - name: build_docker
    pull: if-not-exists
    image: plugins/docker
    privileged: true
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: apt-cache
        path: /var/cache/apt/archives # 将应用打包好的Jar和执行脚本挂载出来
    settings:
      registry: http://192.168.106.8:6082
      insecure: true
      repo: 192.168.106.8:6082/dataelement/bisheng-backend
      tags: [ latest ]
      context: ./src/backend/
      dockerfile: ./src/backend/Dockerfile
      username:
        from_secret: NEXUS_USER
      password:
        from_secret: NEXUS_PASSWORD

trigger:
  branch:
  - main
   
volumes:
- name: bisheng-cache
  host:
    path: /opt/drone/data/bisheng/
- name: apt-cache
  host:
    path: /opt/drone/data/bisheng/apt/
    
